# D:/vue/docker/docker-compose.yml (最终持久化版)

version: '3.8'

services:
  emby-toolkit:
    build: .
    container_name: emby-toolkit
    restart: unless-stopped
    volumes:
      - ./local_data:/config 
    environment:
      - APP_DATA_DIR=/config
      - PUID=1000
      - PGID=1000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=embytoolkit      
      - DB_PASSWORD=embytoolkit 
      - DB_NAME=embytoolkit         
    ports:
      - "5257:5257"
      - "8096:8096"
    networks:
      - emby-net
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5257/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  
  db:
    image: postgres:16-alpine 
    container_name: emby-toolkit-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=embytoolkit      
      - POSTGRES_PASSWORD=embytoolkit 
      - POSTGRES_DB=embytoolkit         
    networks:
      - emby-net
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U embytoolkit -d embytoolkit"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  emby-net:
    driver: bridge
  
volumes:
  postgres_data: