name: Telegram Release Notification

# 触发条件：当发布新的 Release 时
on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            🚀 **新版本发布啦！**
            
            📦 **项目**: ${{ github.repository }}
            🏷 **版本**: ${{ github.event.release.tag_name }}
            👤 **发布者**: ${{ github.event.release.author.login }}
            🔗 **直达链接**: [点击查看 Release](${{ github.event.release.html_url }})
            
            📝 **更新日志**:
            ${{ github.event.release.body }}